//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW2_W1830820
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public double Amount { get; set; }
        public Nullable<int> ContactId { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
